### ISSUE TITLE
Why are you connecting on the first devices in the list?

### ISSUE THREAD

**Issue by magic890** [herrkris/node-rfid#1]
Hi,
I'm wondering why, in this [line](https://github.com/herrkris/node-rfid/blob/master/rfid.js#L31), you're selecting as device the first in the `HID.devices()` list without keeping in consideration the [vendorId and deviceId](https://github.com/herrkris/node-rfid/blob/master/rfid.js#L12) provided?
Moreover if you try calling repeatedly `HID.devices()` the output list ordering is random.

**Comment by herrkris** [comment]
I guess the best answer I can give is: no particular reason. I was just messing around with it and luckily it worked for me.
